"""saas_architecture_consolidated

Revision ID: 10cdca965784
Revises: 4d0affb02ff8
Create Date: 2026-05-07 01:31:14.816551
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '10cdca965784'
down_revision: Union[str, None] = '4d0affb02ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('github_access_token', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('report_destinations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('clickup_task_id', sa.String(length=50), nullable=False),
    sa.Column('schedule', sa.String(length=20), nullable=False),
    sa.Column('times', sa.JSON(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('report_style', sa.String(length=50), nullable=True),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_publications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('commits', schema=None) as batch_op:
        batch_op.alter_column('files_changed', existing_type=sa.INTEGER(), nullable=False, server_default='0')
        batch_op.create_unique_constraint('uix_sha_project', ['sha', 'project_id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('report_style', sa.String(length=50), nullable=False, server_default='misto'))
        batch_op.add_column(sa.Column('tech_stack', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('business_context', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False, server_default='1')) # Default to user 1
        batch_op.create_foreign_key('fk_projects_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=sa.VARCHAR(length=50), nullable=False, server_default='pending')
        batch_op.alter_column('content', existing_type=sa.TEXT(), nullable=False, server_default='')
        batch_op.alter_column('summary', existing_type=sa.TEXT(), nullable=False, server_default='')
        batch_op.alter_column('commit_count', existing_type=sa.INTEGER(), nullable=False, server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('commit_count', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('summary', existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column('content', existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column('status', existing_type=sa.VARCHAR(length=50), nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('business_context')
        batch_op.drop_column('tech_stack')
        batch_op.drop_column('report_style')
        batch_op.drop_column('description')

    with op.batch_alter_table('commits', schema=None) as batch_op:
        batch_op.drop_constraint('uix_sha_project', type_='unique')
        batch_op.alter_column('files_changed', existing_type=sa.INTEGER(), nullable=True)

    op.drop_table('report_publications')
    op.drop_table('report_destinations')
    op.drop_table('users')
    # ### end Alembic commands ###
