"""multi_publisher_architecture

Revision ID: 4d0affb02ff8
Revises: 0001
Create Date: 2026-05-07 00:49:53.113554
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4d0affb02ff8'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    # op.drop_table('apscheduler_jobs')
    op.drop_column('projects', 'clickup_task_id')
    op.drop_column('reports', 'published_at')
    op.drop_column('reports', 'clickup_comment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('clickup_comment_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('reports', sa.Column('published_at', sa.DATETIME(), nullable=True))
    op.add_column('projects', sa.Column('clickup_task_id', sa.VARCHAR(length=255), nullable=False))
    # op.create_table('apscheduler_jobs',
    # sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    # sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    # sa.Column('job_state', sa.BLOB(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
